name: breeze
description: "A lightweight and fast text editor."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.10
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.6.0
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.3.0
  
flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  linux: true
  macos: 
    generate: true
  windows: 
    generate: true
  web:
    generate: true
  image_path: "assets/icons/app_icon.png"